import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "./hook/authContext";

import { Toaster } from "react-hot-toast";
import Navbar from "../../layouts/header/Navbar";
import Footer from "../../layouts/footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        
          <AuthContextProvider>
            <Navbar/>
            <Toaster/> 
            {children}
            <Footer/>
          </AuthContextProvider>
        
      </body>
    </html>
  );
}